name = "Yuki"
license = "MIT"
licenselink = "https://github.com/iCyris/hugo-theme-yuki/blob/master/LICENSE"
description = "Yuki is a cute blog theme for Hugo."
homepage = "https://cyris.pen.moe"
tags = ["blog"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "Cyris"
  homepage = "https://cyris.moe"



